<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7853" started-at="2014-03-20T09:53:06Z" finished-at="2014-03-20T09:53:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7853" started-at="2014-03-20T09:53:06Z" finished-at="2014-03-20T09:53:13Z">
      <class name="com.rstyle.test.TestLogin">
        <test-method status="PASS" signature="dosmth()[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="dosmth" is-config="true" duration-ms="24" started-at="2014-03-20T12:53:06Z" finished-at="2014-03-20T12:53:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dosmth -->
        <test-method status="PASS" signature="loginTest(com.rstyle.struct.UserData, boolean)[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="loginTest" duration-ms="1132" started-at="2014-03-20T12:53:06Z" data-provider="loginTestData" finished-at="2014-03-20T12:53:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.rstyle.struct.UserData@1984427]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.rstyle.struct.UserData, boolean)[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="loginTest" duration-ms="677" started-at="2014-03-20T12:53:07Z" data-provider="loginTestData" finished-at="2014-03-20T12:53:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.rstyle.struct.UserData@c5d01d]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.rstyle.struct.UserData, boolean)[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="loginTest" duration-ms="680" started-at="2014-03-20T12:53:07Z" data-provider="loginTestData" finished-at="2014-03-20T12:53:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.rstyle.struct.UserData@d8573]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.rstyle.struct.UserData, boolean)[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="loginTest" duration-ms="1394" started-at="2014-03-20T12:53:08Z" data-provider="loginTestData" finished-at="2014-03-20T12:53:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.rstyle.struct.UserData@5e50d4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Must not be login with data [ oper1]/[oper1]. But logined. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Must not be login with data [ oper1]/[oper1]. But logined. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.rstyle.test.TestLogin.loginTest(TestLogin.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.rstyle.struct.UserData, boolean)[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="loginTest" duration-ms="1240" started-at="2014-03-20T12:53:10Z" data-provider="loginTestData" finished-at="2014-03-20T12:53:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.rstyle.struct.UserData@12e3194]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Must not be login with data [oper1 ]/[oper1]. But logined. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Must not be login with data [oper1 ]/[oper1]. But logined. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.rstyle.test.TestLogin.loginTest(TestLogin.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.rstyle.struct.UserData, boolean)[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="loginTest" duration-ms="1132" started-at="2014-03-20T12:53:11Z" data-provider="loginTestData" finished-at="2014-03-20T12:53:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.rstyle.struct.UserData@9740de]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="stop()[pri:0, instance:com.rstyle.test.TestLogin@a80e05]" name="stop" is-config="true" duration-ms="1506" started-at="2014-03-20T12:53:12Z" finished-at="2014-03-20T12:53:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- com.rstyle.test.TestLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
